name: rune
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  intl: ^0.19.0
  get_it: ^8.0.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  icons_plus: ^5.0.0
  provider: ^6.1.2
  animated_bottom_navigation_bar: ^1.3.3
  iconsax: ^0.0.8
  url_launcher: ^6.3.1
  # flutter_chess_board: ^1.0.1
  chessground: ^6.2.2
  password_strength: ^0.2.0
  dartchess: ^0.9.2
  image_picker: ^1.1.2
  widget_and_text_animator: ^1.1.5
  fast_immutable_collections: ^10.0.0
  country_state_city: ^0.1.6
  lottie: ^3.1.3
  flutter_bounceable: ^1.2.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.2.3
  email_validator: ^3.0.0
  toastification: ^1.0.0
  mime: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pieces/
    - assets/images/
    - assets/json/
    - assets/images/nfts/
    - assets/svgs/
    - assets/svgs/nfts/
    - assets/svgs/game_buttons/
    - assets/svgs/bottom_nav/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Ojuju
      fonts:
        - asset: assets/fonts/Ojuju-Regular.ttf
        - asset: assets/fonts/Ojuju-Medium.ttf
        - asset: assets/fonts/Ojuju-SemiBold.ttf
        - asset: assets/fonts/Ojuju-Bold.ttf
        - asset: assets/fonts/Ojuju-ExtraBold.ttf

    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
